# Site settings
title: The Seed
description: A multiplayer game designed for AI
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anon Developer
detailed_description: We are building an architecture to make it easier to perform experiments with Reinforcement Learning, bots, and other algorithms. The basis is a server with the game logic, a sample client to receive game state and send player actions, and a renderer to observe how the agents are playing the game. The Goal is to make an environment that is easy to work with, but allows a user to create many complex experiments.
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username: lorem_ipsum
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
